const IMAGES = {
    LOAD: 'LOAD_IMAGES',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAILURE: 'IMAGES_LOAD_FAILURE'

}

const STATS = {
    LOAD: 'LOAD_STATS',
    LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    LOAD_FAILURE: 'STATS_LOAD_FAILURE'
}

export {
    IMAGES,
    STATS
}
